export const sysString = {
  table: {
    checkbox: 'Checkbox',
    no: 'No.',
    well: 'Well',
    sampleId: 'Sample Id',
    result: 'Result',
    type: 'Type',
    comment: 'Comment',
    target: 'Target',
    copiesul: 'Copies/μl',
    ct: 'c(t)',
    gene: 'Gene',
  },
  gnbmenu: {
    home: 'Home',
    setting: 'Setting',
    tabs: 'Tabs',
    info: 'Info',
    help: 'Help',
    assayPack: 'Assay Pack',
  },
  summary: {
    top: {
      summary: 'Summary',
      viewRunReport: 'View Run Report',
    },
    analyzedInfo: {
      analyzedInfo: 'Analyzed Info',
      analyzedDate: 'Analyzed Date',
    },
    pcrInfo: {
      pcrInfo: 'PCR Info',
      pcrDateTime: 'PCR Date & Time',
      pcrEquipment: 'PCR Equipment',
      pcrDataFile: 'PCR Data File',
      plrnFile: 'Plrn File',
      consumables: 'Consumables',
    },
    assayInfo: {
      assayInfo: 'Assay Info',
      assay: 'Assay',
      usage: 'Usage',
      validity: 'Validity',
      samples: 'Samples',
      madeBy: 'Made by',
      total: 'Total',
      valid: 'Valid',
      invalid: 'Invalid',
    },
  },
};
